#!/usr/bin/env python3
"""Convert gpt-image-2 output into RGB332 C arrays + preview PNGs.

Modes:
  single: one image -> one sprite frame
  sheet:  2x2 grid image -> 4 frames (idle_a, idle_b, eat, happy)

Usage:
  python3 convert_sprite.py sheet <in.png> <name> <outdir> [--size 32] [--colors 15]
  python3 convert_sprite.py single <in.png> <name> <outdir> [--size 32] [--colors 15]

Outputs in <outdir>:
  <name>.h            C header: const uint8_t <name>_<frame>[size*size] PROGMEM (RGB332, 0xE3=transparent)
  <name>_<frame>.png  32x32 final (RGBA, transparent bg)
  <name>_preview.png  all frames side by side, 8x nearest upscale, checker bg
"""
import argparse
import sys
from PIL import Image

FRAMES = ["idle_a", "idle_b", "eat", "happy"]
TRANSPARENT_332 = 0xE3  # magenta key


def rgb_to_332(r, g, b):
    v = (r & 0xE0) | ((g & 0xE0) >> 3) | (b >> 6)
    if v == TRANSPARENT_332:  # avoid accidental key collision
        v = 0xE2
    return v


def white_to_alpha(img, thresh=245):
    """Treat near-white background as transparent (gpt-image white bg)."""
    img = img.convert("RGBA")
    px = img.load()
    w, h = img.size
    # flood fill from corners so white highlights inside the body survive
    from collections import deque
    seen = [[False] * w for _ in range(h)]
    dq = deque()
    for x, y in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)]:
        dq.append((x, y))
    while dq:
        x, y = dq.popleft()
        if x < 0 or y < 0 or x >= w or y >= h or seen[y][x]:
            continue
        seen[y][x] = True
        r, g, b, a = px[x, y]
        if r >= thresh and g >= thresh and b >= thresh:
            px[x, y] = (r, g, b, 0)
            dq.extend([(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)])
    return img


def trim_and_square(img, pad_ratio=0.04):
    bbox = img.getchannel("A").getbbox()
    if bbox is None:
        raise SystemExit("empty image after background removal")
    img = img.crop(bbox)
    w, h = img.size
    side = max(w, h)
    pad = int(side * pad_ratio)
    side += 2 * pad
    sq = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    sq.paste(img, ((side - w) // 2, side - pad - h))  # bottom-anchored
    return sq


def downscale_quantize(img, size, colors):
    small = img.resize((size, size), Image.LANCZOS)
    rgb = Image.new("RGB", small.size, (255, 0, 255))
    rgb.paste(small, mask=small.getchannel("A").point(lambda a: 255 if a >= 128 else 0))
    q = rgb.quantize(colors=colors + 1, method=Image.MEDIANCUT, dither=Image.Dither.NONE)
    out = q.convert("RGB")
    # rebuild alpha from magenta-ish pixels
    final = Image.new("RGBA", out.size, (0, 0, 0, 0))
    fp, op = final.load(), out.load()
    for y in range(size):
        for x in range(size):
            r, g, b = op[x, y]
            if r > 200 and b > 200 and g < 80:
                continue
            fp[x, y] = (r, g, b, 255)
    return final


def to_c_array(img, sym):
    px = img.load()
    w, h = img.size
    vals = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            vals.append(TRANSPARENT_332 if a < 128 else rgb_to_332(r, g, b))
    lines = [f"static const uint8_t {sym}[{w * h}] PROGMEM = {{"]
    for i in range(0, len(vals), 16):
        lines.append("  " + ", ".join(f"0x{v:02X}" for v in vals[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


def checker_preview(frames, scale=8):
    size = frames[0].size[0]
    w = size * scale * len(frames) + (len(frames) - 1) * scale
    h = size * scale
    prev = Image.new("RGB", (w, h))
    for y in range(h):
        for x in range(w):
            c = 90 if ((x // 16) + (y // 16)) % 2 else 60
            prev.putpixel((x, y), (c, c, c))
    for i, f in enumerate(frames):
        big = f.resize((size * scale, size * scale), Image.NEAREST)
        prev.paste(big, (i * (size * scale + scale), 0), big)
    return prev


def _write_outputs(args, finals, arrays):
    guard = f"TOI_SPRITE_{args.name.upper()}_H"
    with open(f"{args.outdir}/{args.name}.h", "w") as f:
        f.write(f"// Auto-generated by convert_sprite.py — do not edit by hand\n"
                f"// {args.size}x{args.size} RGB332, transparent key 0x{TRANSPARENT_332:02X}\n"
                f"#ifndef {guard}\n#define {guard}\n#include <pgmspace.h>\n\n")
        f.write("\n\n".join(arrays))
        f.write(f"\n\n#endif // {guard}\n")

    checker_preview(finals).save(f"{args.outdir}/{args.name}_preview.png")

    def as332(img):
        out = Image.new("RGBA", img.size, (0, 0, 0, 0))
        ip, op = img.load(), out.load()
        for y in range(img.size[1]):
            for x in range(img.size[0]):
                r, g, b, a = ip[x, y]
                if a < 128:
                    continue
                v = rgb_to_332(r, g, b)
                r3, g3, b2 = v & 0xE0, (v & 0x1C) << 3, (v & 0x03) << 6
                op[x, y] = (r3 | (r3 >> 3) | (r3 >> 6), g3 | (g3 >> 3) | (g3 >> 6),
                            b2 | (b2 >> 2) | (b2 >> 4) | (b2 >> 6), 255)
        return out

    checker_preview([as332(f) for f in finals]).save(f"{args.outdir}/{args.name}_preview332.png")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("mode", choices=["sheet", "single", "derive"])
    ap.add_argument("infile")
    ap.add_argument("name")
    ap.add_argument("outdir")
    ap.add_argument("--size", type=int, default=32)
    ap.add_argument("--colors", type=int, default=15)
    args = ap.parse_args()

    src = Image.open(args.infile)
    if args.mode == "derive":
        # mechanical fallback: 4 frames derived from one concept image
        img = white_to_alpha(src)
        img = trim_and_square(img)
        fin = downscale_quantize(img, args.size, args.colors)

        def squash75(f):
            w, h = f.size
            nh = int(h * 0.75)
            sq = f.resize((w, nh), Image.NEAREST)
            out = Image.new("RGBA", (w, h), (0, 0, 0, 0))
            out.paste(sq, (0, h - nh))
            return out

        import os
        os.makedirs(args.outdir, exist_ok=True)
        finals, arrays = [], []
        for f, fname in zip([fin, squash75(fin), fin, fin], FRAMES):
            f.save(f"{args.outdir}/{args.name}_{fname}.png")
            finals.append(f)
            arrays.append(to_c_array(f, f"SPR_{args.name.upper()}_{fname.upper()}"))
        _write_outputs(args, finals, arrays)
        print(f"ok {args.name}: derive -> {args.outdir}")
        return

    if args.mode == "sheet":
        w, h = src.size
        cells = [src.crop((0, 0, w // 2, h // 2)), src.crop((w // 2, 0, w, h // 2)),
                 src.crop((0, h // 2, w // 2, h)), src.crop((w // 2, h // 2, w, h))]
        names = FRAMES
    else:
        cells = [src]
        names = ["idle_a"]

    import os
    os.makedirs(args.outdir, exist_ok=True)
    finals, arrays = [], []
    for cell, fname in zip(cells, names):
        img = white_to_alpha(cell)
        img = trim_and_square(img)
        fin = downscale_quantize(img, args.size, args.colors)
        fin.save(f"{args.outdir}/{args.name}_{fname}.png")
        finals.append(fin)
        arrays.append(to_c_array(fin, f"SPR_{args.name.upper()}_{fname.upper()}"))

    _write_outputs(args, finals, arrays)
    print(f"ok {args.name}: {len(finals)} frame(s) -> {args.outdir}")


if __name__ == "__main__":
    main()
