#!/usr/bin/env bash
# Generate secrets.ini for the Stopwatch firmware build.
# WiFi credentials come from arguments; the device token comes from (in order)
# the DEVICE_TOKEN env var, the `akc` keychain helper if installed, or a
# hidden prompt — so it never appears in shell history or files you type.
#
# Usage:
#   WORKER_URL=https://toicamera.<your-subdomain>.workers.dev \
#     ./gen-secrets.sh <ssid1> <pass1> [ssid2] [pass2]
#
# WORKER_URL points at YOUR deployed Worker (see the Worker setup guide (aieo-product.github.io/ToiCamera)).
set -euo pipefail
cd "$(dirname "$0")"

SSID1="${1:?usage: WORKER_URL=https://... ./gen-secrets.sh <ssid1> <pass1> [ssid2] [pass2]}"
PASS1="${2:?missing pass1}"
SSID2="${3:-}"
PASS2="${4:-}"
WORKER_URL="${WORKER_URL:?set WORKER_URL to your deployed Worker URL (deploy worker/ first — see the Worker setup guide (aieo-product.github.io/ToiCamera))}"

if [[ -n "${DEVICE_TOKEN:-}" ]]; then
  TOKEN="$DEVICE_TOKEN"
  TOKEN_SRC="env DEVICE_TOKEN"
elif command -v akc >/dev/null 2>&1 && akc check TOICAMERA_DEVICE_TOKEN >/dev/null 2>&1; then
  TOKEN="$(akc get TOICAMERA_DEVICE_TOKEN --reveal)"
  TOKEN_SRC="akc: TOICAMERA_DEVICE_TOKEN"
else
  read -r -s -p "Device token (same value as the Worker's DEVICE_TOKEN secret): " TOKEN
  echo
  [[ -n "$TOKEN" ]] || { echo "error: empty device token" >&2; exit 1; }
  TOKEN_SRC="prompt"
fi

cat > secrets.ini <<EOF
; Generated by gen-secrets.sh — do not commit (gitignored)
[secrets]
build_flags =
  -DWIFI_SSID1=\\"${SSID1}\\"
  -DWIFI_PASS1=\\"${PASS1}\\"
  -DWIFI_SSID2=\\"${SSID2}\\"
  -DWIFI_PASS2=\\"${PASS2}\\"
  -DWORKER_URL=\\"${WORKER_URL}\\"
  -DDEVICE_TOKEN=\\"${TOKEN}\\"
EOF
echo "secrets.ini written (token from ${TOKEN_SRC})"
