#!/usr/bin/env bash
# Generate secrets.ini for the Stopwatch firmware build.
# WiFi credentials come from arguments; the device token is pulled from the
# macOS Keychain via akc so it never appears in shell history or files you type.
#
# Usage:
#   ./gen-secrets.sh <ssid1> <pass1> [ssid2] [pass2] [cams3-ip]
set -euo pipefail
cd "$(dirname "$0")"

SSID1="${1:?usage: ./gen-secrets.sh <ssid1> <pass1> [ssid2] [pass2] [cams3-ip]}"
PASS1="${2:?missing pass1}"
SSID2="${3:-}"
PASS2="${4:-}"
CAM_IP="${5:-192.168.1.50}"
WORKER_URL="https://toicamera.take-otani.workers.dev"

TOKEN="$(akc get TOICAMERA_DEVICE_TOKEN --reveal)"

cat > secrets.ini <<EOF
; Generated by gen-secrets.sh — do not commit (gitignored)
[secrets]
build_flags =
  -DWIFI_SSID1=\\"${SSID1}\\"
  -DWIFI_PASS1=\\"${PASS1}\\"
  -DWIFI_SSID2=\\"${SSID2}\\"
  -DWIFI_PASS2=\\"${PASS2}\\"
  -DCAM_BASE=\\"http://${CAM_IP}\\"
  -DWORKER_URL=\\"${WORKER_URL}\\"
  -DDEVICE_TOKEN=\\"${TOKEN}\\"
EOF
echo "secrets.ini written (token from akc: TOICAMERA_DEVICE_TOKEN, cam: http://${CAM_IP})"
